Controllers/AdminProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PizzaBuy.Models.Domain;
using PizzaBuy.Models.ViewModel;
using PizzaBuy.Repositories;

namespace PizzaBuy.Controllers
{
    public class AdminProductController : Controller
    {
        private readonly IProductRepository productRepository;

        public AdminProductController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        
        public async Task<IActionResult> Add(AddProductRequest addProductRequest)
        {
            var product = new Product
            {
                ProductName = addProductRequest.ProductName,
                ProductDescription = addProductRequest.ProductDescription,
                ProductPrice = addProductRequest.ProductPrice,
                ProductImage = addProductRequest.ProductImage,
                ProductAvailable = addProductRequest.ProductAvailable,
                Type = addProductRequest.Type,
            };
            await productRepository.AddAsync(product);

            return RedirectToAction("Add");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var productList = await productRepository.GetAllAsync();
            return View(productList);
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            //get the data
            var product = await productRepository.GetAsync(id);

            if(product !=null)
            {
                //map the domain model to view model
                var model = new EditProductRequest
                {
                    Id = product.Id,
                    ProductName = product.ProductName,
                    ProductDescription = product.ProductDescription,
                    ProductPrice = product.ProductPrice,
                    ProductImage = product.ProductImage,
                    ProductAvailable = product.ProductAvailable,
                    Type = product.Type,
                };

                //pass data to view
                return View(model);

            }
            else {
                return View("Edit");

            }
            
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(EditProductRequest editProductRequest)
        {
            //map view model to domain model

            var updatedProduct = new Product
            {
                Id = editProductRequest.Id,
                ProductName = editProductRequest.ProductName,
                ProductDescription = editProductRequest.ProductDescription,
                ProductPrice = editProductRequest.ProductPrice,
                ProductImage = editProductRequest.ProductImage,
                ProductAvailable = editProductRequest.ProductAvailable,
                Type = editProductRequest.Type,

            };

            var updatedProduct1 = await productRepository.UpdateAsync(updatedProduct);

            if(updatedProduct1 != null)
            {
                //show success
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Edit");
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(EditProductRequest editProductRequest)
        {
            var deletedProduct = await productRepository.DeleteAsync(editProductRequest.Id);

            if(deletedProduct != null)
            {
                //show success notification
                return RedirectToAction("List");
            }
            else
            {
                //show error notification
                return RedirectToAction("Edit", new { id = editProductRequest.Id });
            }

        }
    }
}

Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using PizzaBuy.Repositories;

namespace PizzaBuy.Controllers
{
    public class MenuController : Controller
    {
        private readonly IProductRepository productRepository;

        public MenuController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        [HttpGet]
        public async Task<IActionResult> VegMenu()
        {
            var productList = await productRepository.GetAllAsync().ConfigureAwait(false); ;
            return View(productList);
        }

        [HttpGet]
        public async Task<IActionResult> NonVegMenu() 
        {
            var productList = await productRepository.GetAllAsync().ConfigureAwait(false); ;
            return View(productList);
        
        }
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaBuy.Models.Domain;
using PizzaBuy.Models.ViewModel;
using PizzaBuy.Repositories;

namespace PizzaBuy.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IProfileRepository profileRepository;

        public ProfileController(IProfileRepository profileRepository) 
        {
            this.profileRepository = profileRepository;
        }




        //public IActionResult Index()
        //{
        //    return View();
        //}


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var profile = await profileRepository.GetAsync(id.ToString());

            if (profile != null)
            {
                var model = new EditProfileRequest
                {
                    ProfileName = "",
                    ProfileAge = 0,
                    ProfileEmail = profile.Email,
                    ProfileUserName = profile.UserName,
                    ProfileId = id
                    
                };

                return View(model);




            }
            else
            {
                return View("Edit");
                // If the profile is not found, you might want to redirect or show an error view
                // Example: return NotFound("Profile not found");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditProfileRequest editProfileRequest)
        {
            var updatedIdentityUser = new IdentityUser
            {
                UserName = editProfileRequest.ProfileUserName, 
                Email = editProfileRequest.ProfileEmail,

            };

            //code to persist the IdentityUser
            await profileRepository.UpdateAsync1(updatedIdentityUser);

            var updatedProfile = new Profile
            {
                ProfileName = editProfileRequest.ProfileName,
                ProfileAge = editProfileRequest.ProfileAge,
                //ProfileId = editProfileRequest.ProfileId.ToString(),

            };

           // await profileRepository.UpdateAsync(updatedProfile);
            
            


            // code to persist the profile

          //  updatedIdentityUser = await profileRepository.UpdateAsync(updatedProfile);
            //updatedProfile = await profileRepository.UpdateAsync(updatedProfile);

            return RedirectToAction("Index","Home");
        }
    }
}

Views/Shared/NavPartialView.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@* navbar start *@
<section class="menu menu2 cid-u1kYngNZnR" once="menu" id="menu-5-u1kYngNZnR">
    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a asp-controller="Home" asp-action="Index">
                        <img src="/images/pizza-gallery-1.jpeg" style="height: 4.3rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap">
                    <a class="navbar-caption text-black display-4" href="https://mobiri.se">PizzaRave</a>
                </span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-bs-toggle="collapse" data-target="#navbarSupportedContent"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item">
                        <a class="nav-link link text-black display-4" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link text-black display-4" 
                           aria-expanded="false" asp-area="" asp-controller="Menu" asp-action="NonVegMenu">NonVeg</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link text-black display-4" asp-area="" asp-controller="Menu" asp-action="VegMenu">Veg</a>
                    </li>

                    @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle link text-black display-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminProduct" asp-action="Add">Add Product</a>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminProduct" asp-action="List">View Product</a>
                                </li>


                            </ul>

                        </li>
                    }

                </ul>
                @{
                    var user = await signInManager.UserManager.GetUserAsync(User);
                    var userId = user?.Id;
                    
                
                @if(signInManager.IsSignedIn(User))
                {
                   @*  <div class="mbr-text mbr-fonts-style display-7" style="margin-right: 20px">@User?.Identity?.Name</div> *@
                    <div class="navbar-buttons mbr-section-btn" style="margin-right: 20px">
                            <a class="btn btn-primary display-4" asp-area="" asp-controller="Profile" asp-action="Edit" asp-route-id="@userId">@User?.Identity?.Name</a>
                    </div>

                    <p></p>
                    <div class="navbar-buttons mbr-section-btn ">
                        <a class="btn btn-primary display-4" asp-area="" asp-controller="Account" asp-action="Logout">Log Out</a>
                    </div>

                }
                else
                {
                    <div class="navbar-buttons mbr-section-btn" style="margin-right: 20px">
                        <a class="btn btn-primary display-4" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </div>
                    <div class="navbar-buttons mbr-section-btn">
                        <a class="btn btn-primary display-4" asp-area="" asp-controller="Account" asp-action="Register">Join Now</a>
                    </div>
                }
                }
            </div>
        </div>
    </nav>
</section>
@* navbar end *@

Views/Shared/PartialFooterView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<section class="footer3 cid-u1kYngQbzn" once="footers" id="footer-6-u1kYngQbzn">
    <div class="container">
        <div class="row">
            <div class="row-links">
                <ul class="header-menu">
                    <li class="header-menu-item mbr-fonts-style display-5">
                        <a asp-controller="Home" asp-action="Index" class="text-white">Home</a>
                    </li>
                    <li class="header-menu-item mbr-fonts-style display-5">
                        <a asp-controller="Menu" asp-action="NonVegMenu" class="text-white">Non Veg</a>
                    </li>
                    <li class="header-menu-item mbr-fonts-style display-5">
                        <a asp-controller="Menu" asp-action="VegMenu" class="text-white">Veg</a>
                    </li>
                    <li class="header-menu-item mbr-fonts-style display-5">
                        <a href="#" class="text-white">About</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 mt-4">
                <p class="mbr-fonts-style copyright display-7">
                    © 2024 PizzaRave. All Rights Reserved.
                </p>
            </div>
        </div>
    </div>
</section>

Views/Shared/Pay.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<!-- Code By Webdevtrick ( https://webdevtrick.com ) -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Credit Card Payment Form | Webdevtrick.com</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway|Rock+Salt|Source+Code+Pro:300,400,600" rel="stylesheet">
    <link rel="stylesheet" href="style.css">

</head>
<body>

    <div class="payment-title">
        <h1>Payment Information</h1>
    </div>
    <div class="container preload">
        <div class="creditcard">
            <div class="front">
                <div id="ccsingle"></div>
                <svg version="1.1" id="cardfront" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                     x="0px" y="0px" viewBox="0 0 750 471" style="enable-background:new 0 0 750 471;" xml:space="preserve">
                <g id="Front">
                <g id="CardBackground">
                <g id="Page-1_1_">
                <g id="amex_1_">
                <path id="Rectangle-1_1_" class="lightcolor grey" d="M40,0h670c22.1,0,40,17.9,40,40v391c0,22.1-17.9,40-40,40H40c-22.1,0-40-17.9-40-40V40
                            C0,17.9,17.9,0,40,0z" />
                                </g>
                            </g>
                <path class="darkcolor greydark" d="M750,431V193.2c-217.6-57.5-556.4-13.5-750,24.9V431c0,22.1,17.9,40,40,40h670C732.1,471,750,453.1,750,431z" />
                        </g>
                <text transform="matrix(1 0 0 1 60.106 295.0121)" id="svgnumber" class="st2 st3 st4">0123 4567 8910 0000</text>
                <text transform="matrix(1 0 0 1 54.1064 428.1723)" id="svgname" class="st2 st5 st6">JOHN DOE</text>
                <text transform="matrix(1 0 0 1 54.1074 389.8793)" class="st7 st5 st8">cardholder name</text>
                <text transform="matrix(1 0 0 1 479.7754 388.8793)" class="st7 st5 st8">expiration</text>
                <text transform="matrix(1 0 0 1 65.1054 241.5)" class="st7 st5 st8">card number</text>
                <g>
                <text transform="matrix(1 0 0 1 574.4219 433.8095)" id="svgexpire" class="st2 st5 st9">01/23</text>
                <text transform="matrix(1 0 0 1 479.3848 417.0097)" class="st2 st10 st11">VALID</text>
                <text transform="matrix(1 0 0 1 479.3848 435.6762)" class="st2 st10 st11">THRU</text>
                <polygon class="st2" points="554.5,421 540.4,414.2 540.4,427.9 		" />
                        </g>
                <g id="cchip">
                <g>
                <path class="st2" d="M168.1,143.6H82.9c-10.2,0-18.5-8.3-18.5-18.5V74.9c0-10.2,8.3-18.5,18.5-18.5h85.3
                        c10.2,0,18.5,8.3,18.5,18.5v50.2C186.6,135.3,178.3,143.6,168.1,143.6z" />
                            </g>
                <g>
                <g>
                <rect x="82" y="70" class="st12" width="1.5" height="60" />
                                </g>
                <g>
                <rect x="167.4" y="70" class="st12" width="1.5" height="60" />
                                </g>
                <g>
                <path class="st12" d="M125.5,130.8c-10.2,0-18.5-8.3-18.5-18.5c0-4.6,1.7-8.9,4.7-12.3c-3-3.4-4.7-7.7-4.7-12.3
                            c0-10.2,8.3-18.5,18.5-18.5s18.5,8.3,18.5,18.5c0,4.6-1.7,8.9-4.7,12.3c3,3.4,4.7,7.7,4.7,12.3
                            C143.9,122.5,135.7,130.8,125.5,130.8z M125.5,70.8c-9.3,0-16.9,7.6-16.9,16.9c0,4.4,1.7,8.6,4.8,11.8l0.5,0.5l-0.5,0.5
                            c-3.1,3.2-4.8,7.4-4.8,11.8c0,9.3,7.6,16.9,16.9,16.9s16.9-7.6,16.9-16.9c0-4.4-1.7-8.6-4.8-11.8l-0.5-0.5l0.5-0.5
                            c3.1-3.2,4.8-7.4,4.8-11.8C142.4,78.4,134.8,70.8,125.5,70.8z" />
                                </g>
                <g>
                <rect x="82.8" y="82.1" class="st12" width="25.8" height="1.5" />
                                </g>
                <g>
                <rect x="82.8" y="117.9" class="st12" width="26.1" height="1.5" />
                                </g>
                <g>
                <rect x="142.4" y="82.1" class="st12" width="25.8" height="1.5" />
                                </g>
                <g>
                <rect x="142" y="117.9" class="st12" width="26.2" height="1.5" />
                                </g>
                            </g>
                        </g>
                    </g>
                <g id="Back">
                    </g>
                </svg>
            </div>
            <div class="back">
                <svg version="1.1" id="cardback" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                     x="0px" y="0px" viewBox="0 0 750 471" style="enable-background:new 0 0 750 471;" xml:space="preserve">
                <g id="Front">
                <line class="st0" x1="35.3" y1="10.4" x2="36.7" y2="11" />
                    </g>
                <g id="Back">
                <g id="Page-1_2_">
                <g id="amex_2_">
                <path id="Rectangle-1_2_" class="darkcolor greydark" d="M40,0h670c22.1,0,40,17.9,40,40v391c0,22.1-17.9,40-40,40H40c-22.1,0-40-17.9-40-40V40
                        C0,17.9,17.9,0,40,0z" />
                            </g>
                        </g>
                <rect y="61.6" class="st2" width="750" height="78" />
                <g>
                <path class="st3" d="M701.1,249.1H48.9c-3.3,0-6-2.7-6-6v-52.5c0-3.3,2.7-6,6-6h652.1c3.3,0,6,2.7,6,6v52.5
                    C707.1,246.4,704.4,249.1,701.1,249.1z" />
                <rect x="42.9" y="198.6" class="st4" width="664.1" height="10.5" />
                <rect x="42.9" y="224.5" class="st4" width="664.1" height="10.5" />
                <path class="st5" d="M701.1,184.6H618h-8h-10v64.5h10h8h83.1c3.3,0,6-2.7,6-6v-52.5C707.1,187.3,704.4,184.6,701.1,184.6z" />
                        </g>
                <text transform="matrix(1 0 0 1 621.999 227.2734)" id="svgsecurity" class="st6 st7">985</text>
                <g class="st8">
                <text transform="matrix(1 0 0 1 518.083 280.0879)" class="st9 st6 st10">security code</text>
                        </g>
                <rect x="58.1" y="378.6" class="st11" width="375.5" height="13.5" />
                <rect x="58.1" y="405.6" class="st11" width="421.7" height="13.5" />
                <text transform="matrix(1 0 0 1 59.5073 228.6099)" id="svgnameback" class="st12 st13">John Doe</text>
                    </g>
                </svg>
            </div>
        </div>
    </div>
    <div class="form-container">
        <div class="field-container">
            <label for="name">Name</label>
            <input id="name" maxlength="20" type="text">
        </div>
        <div class="field-container">
            <label for="cardnumber">Card Number</label><span id="generatecard">generate random</span>
            <input id="cardnumber" type="text" pattern="[0-9]*" inputmode="numeric">
            <svg id="ccicon" class="ccicon" width="750" height="471" viewBox="0 0 750 471" version="1.1" xmlns="http://www.w3.org/2000/svg"
                 xmlns:xlink="http://www.w3.org/1999/xlink">
            </svg>
        </div>
        <div class="field-container">
            <label for="expirationdate">Expiration (mm/yy)</label>
            <input id="expirationdate" type="text" pattern="[0-9]*" inputmode="numeric">
        </div>
        <div class="field-container">
            <label for="securitycode">Security Code</label>
            <input id="securitycode" type="text" pattern="[0-9]*" inputmode="numeric">
        </div>
    </div>


    <script src='https://cdnjs.cloudflare.com/ajax/libs/imask/3.4.0/imask.min.js'></script>
    <script src="function.js"></script>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaBuy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PizzaBuy.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="~/css/mobirise2.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/style1.css">
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="~/css/StyleSheet1.css">
    <link rel="stylesheet" href="~/css/StyleSheet2.css">
    <link rel="stylesheet" href="/css/StyleSheet3.css">
    <link rel="stylesheet" href="~/css/StyleSheet4.css">
    <link rel="stylesheet" href="~/css/StyleSheet5.css">
    <link rel="stylesheet" href="~/css/StyleSheet6.css">
    <link rel="stylesheet" href="~/css/StyleSheet7.css">
    <link rel="stylesheet" href="~/css/StyleSheet8.css">
    <link rel="stylesheet" href="~/css/StyleSheet9.css">
    <link rel="stylesheet" href="~/css/StyleSheet10.css">
    <link rel="stylesheet" href="~/css/StyleSheet11.css">
    <link rel="preload" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap"></noscript>
    <link rel="preload" as="style" href="~/css/additional.css">
    <link rel="stylesheet" href="~/css/additional.css" type="text/css">
    <style>
        :root {
            --background: #F1EAE8;
            --dominant-color: #772F1A;
            --primary-color: #F58549;
            --secondary-color: #EEC170;
            --success-color: #32D98C;
            --danger-color: #DB3040;
            --warning-color: #FFC20C;
            --info-color: #18CEF3;
            --background-text: #000000;
            --dominant-text: #FFFFFF;
            --primary-text: #000000;
            --secondary-text: #000000;
            --success-text: #000000;
            --danger-text: #FFFFFF;
            --warning-text: #000000;
            --info-text: #000000;
        }</style>
</head>
<body>
    @await Html.PartialAsync("NavPartialView")
   @*  <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <li class="nav-item dropdown nav-link link text-black display-7">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" asp-area="" asp-controller="AdminProduct" asp-action="Add">Add Product</a>
                        <li>
                            <a class="dropdown-item" asp-area="" asp-controller="AdminProduct" asp-action="List">View Product</a>
                        </li>


                    </ul>

                </li>


            </div>

        </nav>
        <nav>

        </nav>
    </header> *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>@await Html.PartialAsync("PartialFooterView")</footer>
    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PizzaBuy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="/js/formid.min.js"></script>
    <script src="/js/index.js"></script>
    <script src="/js/navbar-dropdown.js"></script>
    <script src="/js/script.js"></script>
    <script src="/js/smooth-scroll.js"></script>
    <script>

        (function () {
            var animationInput = document.createElement('input');
            animationInput.setAttribute('name', 'animation');
            animationInput.setAttribute('type', 'hidden');
            document.body.append(animationInput);
        })();

    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>